from recipes_parser.parsers.ingredients_parser import IngredientsParser


class TestIngredientsParser:
    def test_read_videos(self):
        def handle_result(videos_with_ingredients, output_path):
            assert len(videos_with_ingredients) == 63

        parser = IngredientsParser('../resources/videos-output', '.', handle_result)
        parser.run()

    def test_extract_ingredients_section(self):
        description = "LEARN HOW TO MAKE JAPANESE WAKAME SEAWEED SALAD AT HOME\n\nLAY HO MA!!  This is by far one of my favourite salads of all time.  It's super fresh, crunchy, and packed with incredible flavour.  This salad goes real well with sushi or really just on it's own!  Join me in this episode and learn how to make this easy Japanese wakame seaweed salad recipe.  Let's begin\n\nIngredients: \n3 cups water \n15g wakame dried seaweed \n1 cup arugula (packed) \n1/4 cup corn\r\n1/4 cup edamame \n1/2 heirloom tomato\r\n1 1/2 tbsp cane sugar \n1 tbsp rice vinegar \n1 1/2 tbsp soy sauce \n1 tsp toasted sesame oil\r\n2 tbsp white sesame seeds \n1/4 cup carrot (shredded) \r1/4 cup daikon (shredded)\r\n\nDirections:\n1. Bring the water to boil.  Then, turn off the heat and soak the dried seaweed in the hot water for a few minutes\r2. Strain out the seaweed through a colander keeping the water for another recipe.  Rinse the seaweed with some cold running water\n3. Add the cane sugar, rice vinegar, soy sauce, sesame oil, and 1 tbsp of white sesame seeds to a small mason jar.  Seal the lid and give it a good shake\r\n4. Roughly chop the seaweed and add to a large mixing bowl along with the arugula, corn, edamame, and tomatoes.  Pour in 3/4 of the dressing and mix\r5. Assemble your salad by dividing and scooping the salad into your serving bowls.  Then, divide and top the salad with the shredded carrot and shredded daikon.  \r\n6. Spoon over a little more of the dressing and sprinkle with the remaining white sesame seeds\r\n\n\nORDER YOUR SIGNED VEGAN RAMEN COOKBOOK + GET YOUR FREE E-BOOK + TAKE YOUR VEGAN SUSHI MASTERCLASS HERE:\nhttps://www.yeungmancooking.com\n\nIf you enjoyed this episode and would love to see more, remember to like, comment, and subscribe so that you won't miss a single episode!\n\nHong Kong born Canadian, Wil Yeung is an international photographer, filmmaker, entrepreneur, violinist, and YouTube chef.  He immigrated to Canada when he was a young boy carrying with him his ability to speak Cantonese and some broken English.  Much of his culinary aspirations stem from his background in the visual and musical art spaces.  Whether you're plant based or plant based curious, Wil believes that learning how to make food can really change your life and of those around you.\n\nSTAY IN THE LOOP ON SOCIAL MEDIA!\nWil's Recipes on Instagram:  @mr_wilyeung\nWil's Recipes on Facebook:  fb.me/mrwilyeung\nWil's Photography + Video on Instagram: @wyphotography.com\nWil's Photography + Video on Facebook: wyphotography\n\nYou are watching:\nhttps://youtu.be/06Joz01YmEY"
        parser = IngredientsParser('', '')
        result = parser.extract_ingredients_section_from_text(description)
        assert result == " \n3 cups water \n15g wakame dried seaweed \n1 cup arugula (packed) \n1/4 cup corn\r\n1/4 cup edamame \n1/2 heirloom tomato\r\n1 1/2 tbsp cane sugar \n1 tbsp rice vinegar \n1 1/2 tbsp soy sauce \n1 tsp toasted sesame oil\r\n2 tbsp white sesame seeds \n1/4 cup carrot (shredded) \r1/4 cup daikon (shredded)\r\n\n"
